"use client";

import { useState, useTransition } from "react";
import { toast } from "sonner";
import { generatePractice } from "@/lib/actions/practice";
import type { PracticeSet } from "@/lib/llm/generate-practice";

export function PracticeGenerator({
  students,
}: {
  students: { id: string; name: string }[];
}) {
  const [topic, setTopic] = useState("");
  const [studentId, setStudentId] = useState("");
  const [set, setSet] = useState<PracticeSet | null>(null);
  const [isPending, startTransition] = useTransition();

  function submit(e: React.FormEvent) {
    e.preventDefault();
    if (!topic.trim()) {
      toast.error("Enter a topic first");
      return;
    }
    startTransition(async () => {
      const res = await generatePractice({
        topic,
        studentId: studentId || undefined,
      });
      if (res.ok && res.set) {
        setSet(res.set);
      } else {
        toast.error(res.error ?? "Couldn't generate practice");
      }
    });
  }

  return (
    <div>
      <form
        onSubmit={submit}
        className="mt-6 rounded-2xl border border-brand-mist bg-white p-5"
      >
        <div className="flex flex-wrap items-end gap-4">
          <label className="flex-1 text-xs text-brand-ink/60">
            Topic
            <input
              value={topic}
              onChange={(e) => setTopic(e.target.value)}
              placeholder="Converting fractions, decimals and percentages"
              className="mt-1 block w-full rounded-lg border border-brand-mist px-3 py-2 text-sm text-brand-plum focus:outline-none"
            />
          </label>
          <label className="text-xs text-brand-ink/60">
            For (optional)
            <select
              value={studentId}
              onChange={(e) => setStudentId(e.target.value)}
              className="mt-1 block rounded-lg border border-brand-mist bg-white px-3 py-2 text-sm text-brand-plum focus:outline-none"
            >
              <option value="">Any student</option>
              {students.map((s) => (
                <option key={s.id} value={s.id}>
                  {s.name}
                </option>
              ))}
            </select>
          </label>
          <button
            type="submit"
            disabled={isPending}
            className="rounded-lg bg-brand-plum px-5 py-2 text-sm font-medium text-brand-cream transition-colors hover:bg-brand-plum-mid disabled:opacity-50"
          >
            {isPending ? "Writing…" : "Generate"}
          </button>
        </div>
        <p className="mt-3 text-xs text-brand-ink/45">
          Fresh questions, written in your voice. Review before sending to a
          student.
        </p>
      </form>

      {set ? (
        <div className="mt-6 rounded-2xl border border-brand-mist bg-white p-6">
          {set.greeting ? (
            <p className="text-sm leading-relaxed text-brand-ink/80">
              {set.greeting}
            </p>
          ) : null}

          <ol className="mt-4 flex flex-col gap-4">
            {set.questions.map((q, i) => (
              <li key={i} className="flex gap-3">
                <span className="font-display text-lg text-brand-sage">
                  {i + 1}
                </span>
                <div>
                  <p className="text-sm leading-relaxed text-brand-ink/85">
                    {q.prompt}
                  </p>
                  {q.hint ? (
                    <p className="mt-1 text-xs italic text-brand-ink/55">
                      Hint: {q.hint}
                    </p>
                  ) : null}
                </div>
              </li>
            ))}
          </ol>

          {set.closing ? (
            <p className="mt-5 text-sm leading-relaxed text-brand-ink/80">
              {set.closing}
            </p>
          ) : null}

          {set.model ? (
            <p className="mt-5 border-t border-brand-mist pt-3 text-xs text-brand-ink/40">
              Generated by {set.model}
            </p>
          ) : null}
        </div>
      ) : null}
    </div>
  );
}
