"use client";

import { useState, useTransition } from "react";
import { toast } from "sonner";
import { generateWeeklyReport } from "@/lib/actions/reports";
import type { WeeklyReport } from "@/lib/llm/generate-report";

/**
 * On-demand weekly parent note (read-only — nothing is persisted in week 1).
 * One student → a single "Write this week's note" button. Many students (staff)
 * → a picker first. Mirrors the practice-generator interaction.
 */
export function WeeklyReportGenerator({
  students,
}: {
  students: { id: string; name: string }[];
}) {
  const single = students.length === 1;
  const [studentId, setStudentId] = useState(single ? students[0].id : "");
  const [report, setReport] = useState<WeeklyReport | null>(null);
  const [isPending, startTransition] = useTransition();

  function write() {
    if (!studentId) {
      toast.error("Pick a student first");
      return;
    }
    setReport(null);
    startTransition(async () => {
      const res = await generateWeeklyReport({ studentId });
      if (res.ok && res.report) {
        setReport(res.report);
      } else {
        toast.error(res.error ?? "Couldn't write the note");
      }
    });
  }

  async function copyNote() {
    if (!report) return;
    const text = [report.greeting, report.body, report.signoff]
      .map((s) => s?.trim())
      .filter(Boolean)
      .join("\n\n");
    try {
      await navigator.clipboard.writeText(text);
      toast.success("Note copied — paste it into WhatsApp");
    } catch {
      toast.error("Couldn't copy. Select and copy it manually.");
    }
  }

  return (
    <div className="rounded-2xl border border-brand-mist bg-white p-5">
      <div className="flex flex-wrap items-end gap-4">
        {single ? (
          <p className="flex-1 text-sm font-medium text-brand-plum">
            {students[0].name}
          </p>
        ) : (
          <label className="flex-1 text-xs text-brand-ink/60">
            Student
            <select
              value={studentId}
              onChange={(e) => {
                setStudentId(e.target.value);
                setReport(null);
              }}
              className="mt-1 block w-full rounded-lg border border-brand-mist bg-white px-3 py-2 text-sm text-brand-plum focus:outline-none"
            >
              <option value="">Pick a student</option>
              {students.map((s) => (
                <option key={s.id} value={s.id}>
                  {s.name}
                </option>
              ))}
            </select>
          </label>
        )}
        <button
          type="button"
          onClick={write}
          disabled={isPending}
          className="rounded-lg bg-brand-plum px-5 py-2 text-sm font-medium text-brand-cream transition-colors hover:bg-brand-plum-mid disabled:opacity-50"
        >
          {isPending ? "Writing…" : "Write this week's note"}
        </button>
      </div>
      <p className="mt-3 text-xs text-brand-ink/45">
        A short progress note from this week&apos;s attendance, in your voice.
        Review before sharing.
      </p>

      {report ? (
        <div className="mt-5 rounded-xl border border-brand-mist bg-brand-cream/40 p-5">
          {report.greeting ? (
            <p className="text-sm leading-relaxed text-brand-ink/85">
              {report.greeting}
            </p>
          ) : null}
          {report.body ? (
            <p className="mt-3 whitespace-pre-line text-sm leading-relaxed text-brand-ink/85">
              {report.body}
            </p>
          ) : null}
          {report.signoff ? (
            <p className="mt-3 text-sm leading-relaxed text-brand-ink/85">
              {report.signoff}
            </p>
          ) : null}
          <div className="mt-5 flex items-center justify-between gap-3 border-t border-brand-mist pt-3">
            <button
              type="button"
              onClick={copyNote}
              className="rounded-lg border border-brand-plum/30 px-3 py-1.5 text-xs font-medium text-brand-plum transition-colors hover:bg-brand-plum/[0.06]"
            >
              Copy note
            </button>
            {report.model ? (
              <p className="text-xs text-brand-ink/40">
                Generated by {report.model}
              </p>
            ) : null}
          </div>
        </div>
      ) : null}
    </div>
  );
}
